### ISSUE TITLE
[Feature request] 64-bit bank support

### ISSUE THREAD

**Issue by sylvia-leaf** [SFe-Team-was-taken/SFeReferenceImplementation_Core#11]
### Problem

The SFe specification has infrastructure for a 64-bit version of the format, however only the 32-bit format is supported.

### Description

Add support for 64-bit SFe banks, allowing banks larger than 4GiB.

### Alternatives

Only implementing 32-bit SFe, but ideally the reference implementation should support anything and everything.

**Comment by sylvia-leaf** [comment]
@spessasus 64-bit support in SFe is as simple as:

- riff64 format
- sfen instead of sfbk
- ifil = sfvx
- xshdr for 64-bit support

This shouldn't be too difficult to implement, right?

**Comment by sylvia-leaf** [comment]
@spessasus 64-bit support has now been implemented, however:
- It has not been tested.
- It is not yet implemented in RMIDI.

Because it would be very difficult to find a 4GB bank that could be used for testing, I don't know if it works.

**Comment by sylvia-leaf** [comment]
Before I do this, what would be the file size limit for Chrome before I should move to Firefox?

**Comment by stgiga** [comment]
BWTC32Key on larger files ALSO loves Firefox.

**Comment by sylvia-leaf** [comment]
Alright, I've got Firefox working. SpessaSynth loads HiDef perfectly fine on Firefox.

Now I might be stupid but where even is this copyPresets function? I checked the code and there is no reference to a copyPresets function...

**Comment by spessasus** [comment]
Sorry, it's called "clonePreset" :-)

https://github.com/spessasus/spessasynth_core/blob/master/src%2Fsoundfont%2Fbasic_soundfont%2Fbasic_soundbank.js

**Comment by sylvia-leaf** [comment]
I've made an attempt to add 64-bit write support. It includes almost all of the SF2/SFe write code. DLS won't ever be 64-bit so I didn't add it there, and the RMIDI writer will be implemented later.

I would test this with Spessafont, but I can't get it to use this version of spessasynth_core instead of the regular version. How would I load this version of the spessasynth_core instead?

**Comment by sylvia-leaf** [comment]
So, I've been attempting to add support for writing the ISFe chunk. However, when getting the soundbank information from write.js, the sfeInfo property is always empty, regardless of its value from soundfont.js. 

Why is this the case? Is it because of the SFeInfo class, or is it something else?

**Comment by sylvia-leaf** [comment]
The sfeInfo property was always empty because SpessaFont did not have a way of recognising it. This has been fixed.

**Comment by sylvia-leaf** [comment]
64-bit read and write support is now (mostly) done:

- Tested with files below 4GB, read and write both work.
- Not yet tested with files above 4GB.
- SF2 and SFe are supported.
- RMIDI is not currently supported (but will be for future version of SFe!).
- DLS won't ever be 64-bit.

**Comment by spessasus** [comment]
@stgiga I think you forgot that the reference implementation has the sf2-> DLS conversion in it, and from my testing it's more accurate than the Awave one, as it converts a lot of modulators to articulators, so complex sf2s lime general user are almost lossless in sound when doing sf2->dls->sf2 (of course you can't convert back to sf2 without xdta, as DLS requires flattening)

@sylvia-leaf , how are you for sure going to implement 64-bit since JavaScript's bit operations are 32-bit?

**Comment by stgiga** [comment]
Awave added stuff, and JS can do 64bit via grouped 32bit values.

**Comment by spessasus** [comment]
You know, how about we replace driff in favor of the riff64? It's not like riff64 is limited.

**Comment by sylvia-leaf** [comment]
Let's leave dynamic RIFF in, because it's more efficient than RIFS, and also allows long identifiers, fourCC is a bit limited.

**Comment by sylvia-leaf** [comment]
Further development of 64-bit support will likely wait until indexedbytearray is replaced with writing to the file directly. Progress will be made on adding functions such as lsb support and containerisation.
